config/routes.rb
Coworking::Application.routes.draw do
  devise_for :users

  resources :subscribers, :posts

  root :to => "application#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.is_admin?(user)
      can :manage, :all
    end

    if user.is_guest?(user)
      can [:create], Subscriber
      can [:read], Post
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  validates_uniqueness_of :email
  validates_format_of :email, :with => %r{^(?:[_a-z0-9-]+)(\.[_a-z0-9-]+)*@([a-z0-9-]+)(\.[a-zA-Z0-9\-\.]+)*(\.[a-z]{2,4})$}i

  scope :permanent, lambda { 
          where("subscribers.interest = ?", Settings.interests[2])
      }
  scope :short, lambda { 
          where("subscribers.interest = ?", Settings.interests[0])
      }
  scope :medium, lambda { 
          where("subscribers.interest = ?", Settings.interests[1])
      }

  def name
    return "#{self.firstname} #{self.lastname}"
  end

  def to_s
    llm = ""
    llm += "#{self.name} : #{self.email}\n"
    llm += "#{self.status}\n"
    llm += "#{self.interest}\n"
    llm += "#{self.work_field}\n\n"
    llm += "#{self.comment}\n"
    return llm
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def is_admin?(current_user)
    return true if current_user.email != ""
  end

  def is_guest?(current_user)
    return true unless current_user.email != ""
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  authorize_resource :class => "Post"
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_filter :authenticate_user!, :except => [:create, :new]
  authorize_resource :class => "Subscriber"

  def new
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.new
    @subscriber.firstname = params[:subscriber][:firstname]
    @subscriber.lastname = params[:subscriber][:lastname]
    @subscriber.email = params[:subscriber][:email]
    @subscriber.status = params[:subscriber][:status]
    @subscriber.interest = params[:subscriber][:interest]
    @subscriber.work_field = params[:subscriber][:work_field]
    @subscriber.comment = params[:subscriber][:comment]
    if @subscriber.save
      Notification.new_sub(@subscriber.id).deliver
      Notification.thanks_new(@subscriber.id).deliver
      redirect_to :root, :notice => "Merci #{@subscriber.firstname} ! Vous allez recevoir un email de confirmation"
      return
    else
      render :action => "new"
    end
    
  end

  def index
    @subscribers = Subscriber.find(:all, :order => "interest ASC")
  end

  def destroy
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy
    redirect_to :action => :index
  end

  protected
  def pp_errors(errors)
    llm = ""
    errors.keys.each do |k|
      llm += "#{k} : #{errors[k].first}"
    end
    return llm
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/application/index.html.haml
%div.grid_12.prefix_2

  %div#short
    %div.zap
      %h2 ?
      %ul
        %li un lieu partagé de travail dans un esprit détendu et ouvert
        %li un espace qui soit plus proche d'une colocation que d'une location de coin de table
        %li pour des indépendants, étudiants et TPE
        %li dans Toulouse, à moins de 15 minutes à pied d'un métro
        %li
          inspiré de
          = link_to "IndyHall", "http://www.indyhall.org"
          ,
          = link_to "DevNuts", "http://www.devnuts.com/"
          &
          = link_to "NWC", "http://nwc.co/"
      %div#toggle_short
        = link_to "Dites m'en plus !", nil, :remote => true
  %div#toggle_long
    = link_to "Dites m'en moins !", nil, :remote => true
  %div.clear

%div.clear
%div.grid_14.prefix_1
  %div#long
    %div.zap
      %h2 Quoi ?

      %ul
        %li un lieu partagé de travail
        %li un esprit détendu, ouvert, hétérogène et mixte (penser open space, les canap' en plus, avec les jeux de carte du photographe freelance et les figurines de l'admin unix, ...)
        %li une connection internet correcte (en up et down, dépendra du lieu)
        %li peut être des services supplémentaires (stockage sécurisé de données, etc ...)
        %li un espace de travail qui soit aussi un espace d'échange et de partage
        %li un espace qui soit plus dans l'esprit d'une collocation que d'une simple location d'un coin de table, d'une chaise et d'une connection wifi

    %div.zap
      %h2 Qui ?

      %ul
        %li des indépendants qui aiment bien bosser de chez eux mais qui aiment aussi bosser avec des gens de divers horizons
        %li des télé-travailleurs qui aiment bien bosser avec des collègues, même s'ils ne sont pas de la même société qu'eux
        %li de très petite entreprise pour les mêmes raisons que les deux précédents (< 5 personnes)
        %li des étudiants en thèse qui cherchent un espace un peu atypique pour bosser
        %li des personnes dont le travail est "portable"

      %p Pas de domaine spécifique non plus : informatique, graphisme, design, physique, lettres, ...


    %div.zap
      %h2 Pourquoi ?

      %p Bosser chez soi c'est sympa, mais être avec des gens favorise un esprit d'émulation, la créativité et les projets.

      %p
        = link_to "IndyHall", "http://www.indyhall.org"
        , un espace de coworking à Philadephie (USA) liste notament les points suivants dans leur faq :

      %div.citation
        %ul
          %li.citation
            Collaboration: un des grands bénéfices du travail dans un espace de
            %em coworking
            est que vous rencontrerez toute sorte de gens dotés de toute sorte de connaissances.
          %li.citation Ouverture: Nous croyons dans la transparence et l'ouverture. Dans un monde où les gens sont libres mais pas les idées seulement quelques uns en tirent profit. Lorsque les idées sont libres alors tout le monde en tire bénéfice. Ainsi nous encourageons les espaces ouverts et les discussions. IndyHall est une Communauté basée sur la Confiance.
          %li.citation
            Communauté : les connections et l'entraide fleurissent ici. C'est important que tous donnent et recoivent de la forte communauté (internationale) que le
            %em coworking
            est devenu.
          %li.citation Accessibilité : Afin d'être complètement ouvert nous devons faire les efforts pour être accessible à tous. La diversité est au coeur du succès de notre communauté. Cela signifie que notre projet est de construire un espace qui soit accessible à la fois financièrement et physiquement. Nous sommes dédiés à ce principe et encourageons les commentaires pour nous permettre de le rendre encore plus accessible.
          %li.citation Durabilité du projet : la durabilité est une mission double pour nous : non seulement le partage des ressources est généralement une pratique écologique pour les individus et les entreprises, mais nos bases entreprenariales sont basées sur des relations et échanges durables. Chaque décision est mesurée sur sa possibilité a être soutenue par la communauté sur le long terme.

        %p.note
          %em
            extrait de 
            = link_to "Indy Hall Coworking Faq", "http://www.indyhall.org/coworking-faqs/"

    %div.zap
      %h2 Comment ?

      %p Deux possibilités s'offrent à nous :
      %ul
        %li
          un espace de
          %em coworking
          privé, pour un nombre restreint de personnes avec une grande majorité de permanents
        %li
          un espace de
          %em coworking
          ouvert, avec des formules, façons IndyHall ou NWC

      %p L'un pouvant se transformer en l'autre en fonction des évolutions évidement, mais les deux n'impliquent pas les mêmes dynamiques. L'un se veut essentiellement une "colloc" l'autre peut être beaucoup plus large que ça et favoriser les passages, échanges, etc ...

      %h3 Dans les deux cas

      %ul
        %li un espace principal avec une ou plusieurs grandes tablées sur lesquelles chacun peut s'installer plus ou moins sédentairement
        %li un espace plus petit pour s'isoler pour une réunion ou un coup de fil
        %li un espace détente avec un canapé et de quoi se faire des boissons chaudes
        %li des tableaux blancs pour pouvoir laisser s'exprimer la créativité

      %h3 Dans le cas d'un coworking fermé
    
      %ul
        %li 6 à 8 permanents, et quelques uns en non permanents (un jour à trois jours par semaine)
        %li des formules suivants les usages, mais avec une forte préférence pour les permanents (au moins dans un premier temps) pour assurer le paiement du loyer

      %h3 Dans le cas d'un coworking ouvert

      %ul
        %li pour un début : 10 à 15 personnes max pour ne pas se marcher dessus non plus (7 à 10 permanents (7/7), et environ autant à géométrie variable)
        %li un système similaire à IndyHall ou NWC avec des formules suivants les usages de chacun : 1 jour de temps en temps, jusqu'à 3 jours par semaine, tous les jours de la semaine, la nuit ... avec des tarifs raisonnables dans les deux sens : accessible mais permettant d'assurer la pérénité du lieu à moyen et long terme.

      %p
        Je vous conseille la lecture de :
        = link_to "Indy Hall Coworking FAQ", "http://indyhall.org/coworking-faqs/"
        (anglais), la video expliquant la
        = link_to "philosophie derrière citizen space", "http://citizenspace.us/about/our-philosophy/"
        (anglais), la 
        = link_to "FAQ du NWC", "http://nwc.co/faq/"
        (anglais), et
        = link_to "Coworking Lille", "http://www.coworkinglille.com/index.php"
        (francais).

      %p Ce que comprendraient les formules :
      %ul
        %li place assise
        %li un bureau
        %li accès internet
        %li boisson chaude à volonté (eau, thé, café) si vous fournissez votre mug (compris dans le prix en fait, ou bien ?)
        %li accès aux évènements et réduction pour les boissons/repas lors de ces évènements

    %div.zap
      %h2 Où ?

      %lu
        %li dans Toulouse, si possible intra Muros, à moins de 15 minutes à pieds d'une station de métro et pas loin de petits restaus sympas
        %li dans un appart, un loft, ancien entrepot, ou une maison
        %li là où il y a un accès ADSL de qualité, voir, si possible, de la fibre optique

    %div.zap
      %h2 Inscription

      %p Le projet commence juste, il nous faut donc commencer par essayer de se connaître, discuter des idées ci dessus, savoir qui serait partant pour des formules complètes (5j/7) ou semi complètes (3j/7).

      %p Une fois un noyau de personnes établi nous pourrons discuter des moyens financiers dont nous disposons pour commencer et quel taille de local nous pouvons chercher.

      %p Une fois le projet lancé, un lieu trouvé, loué, et nous installés, nous pourrons voir comment intégrer de nouvelles personnes.

      %p Evidement ceci est une aventure humaine, comme toute aventure humaine elle comportera des hauts et des bas, des couacs et des hourras, donc il faudra prévoir quelques règles de vie évidement ... Mais chaque chose en son temps ...

    %div.zap
      %h2 T'es qui ?
    
      %p Thomas Riboulet, consultant indépendant en informatique. J'ai passé quelques temps à bosser ici et là, chez moi, dans des cafés, des bureaux, j'ai envie de créer un espace qui me convienne un peu mieux en y retrouvant l'ambiance open source en open space, avec une bonne touche de labo d'université ou de grande école.
    
      %p
        Après avoir discuté de l'idée avec mes camarades de jeu de
        = link_to "Toulouse.rb", "http://www.toulouserb.org"
        reçus quelques échos de ceux ci et de leurs contacts, j'ai décidé de lancer ce petit site pour faire un tour de ceux qui sont intéressés.

  %div.zap
  
    %h2 On signe où ?

    %p#short_notice
      Le projet en est en phase d'étude, nous cherchons à regrouper les personnes intéressées.
    %p
      Si vous êtes intéressé
      = link_to "inscrivez vous !", new_subscriber_path

  %div.zap

    %h2 Discuter
    
    %p
      Tous les jours entre 10h et 12h sur
      = link_to "Campfire", "https://arbousierinfo.campfirenow.com/d858e"
    %p
      Sur twitter/status.net : #taucw

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= Settings.site_name
    %link{:href => "http://fonts.googleapis.com/css?family=Quattrocento", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "http://fonts.googleapis.com/css?family=Permanent+Marker", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "http://fonts.googleapis.com/css?family=Expletus+Sans:500", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "http://fonts.googleapis.com/css?family=Indie+Flower", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "http://fonts.googleapis.com/css?family=Cuprum", :rel => "stylesheet", :type => "text/css"}
    = stylesheet_link_tag "reset.css"
    = stylesheet_link_tag "text.css"
    = stylesheet_link_tag "960.css"
    = stylesheet_link_tag "style"
    = javascript_include_tag "jquery.js", "rails.js", "application.js", "analytics.js"
    = csrf_meta_tag
  %body

    %div.container_16{:id => "main_grid"}
      %div#logo_container
        %div#logo
          = link_to image_tag("/images/tau_banner.png", :width => "90px"), root_url
      %div#menu
        = link_to "Index", root_url
        \::
        = link_to "Blog", posts_path
      %div.clear
      %div#twitter
        %h2 #taucw@twitter
      %div#banner
        %div.grid_16
          = notice
          = alert
        %div.clear
      %div#content
        = yield
      %div.clear
      %div#footer
        %div.grid_16.footer
          %div.footer_content
            = Settings.site_name
            = link_to "Arbousier.info", "http://www.arbousier.info"
        %div.clear

app/views/notification/new_sub.text.erb
Bonjour,

Nouvel inscrit :

<%= @subscriber.to_s %>

-- 
<%= Settings.site_name %>

app/views/notification/thanks_new.text.erb
Bonjour,

Merci de vous être inscrit pour le projet <%= Settings.site_name %>

-- 
Thomas Riboulet

app/views/posts/_form.html.haml
= form_for @post do |f|
  -if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  %p
    Title
    = f.text_field :title

  %p
    Content (
    = link_to "markdown", "http://daringfireball.net/projects/markdown/"
    )
  = f.text_area :content, :cols => 100, :lines => 80
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%div.grid_12.prefix_2
  %h1 Editing post

  = render 'form'

  = link_to 'Show', @post
  \|
  = link_to 'Back', posts_path

app/views/posts/index.html.haml
- if current_user
  %div.grid_12.prefix_2
    %h1 Listing posts

    %table
      %tr
        %th Title
        %th Date
        %th Actions

      - @posts.each do |post|
        %tr
          %td= post.title
          %td= post.created_at.strftime("%d/%m/%Y")
          %td
            = link_to 'Show', post
            = link_to 'Edit', edit_post_path(post)
            = link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete

    %br

    = link_to 'New Post', new_post_path
- else
  %div.grid_12.prefix_2
    - if @posts.count > 0
      - @posts.each do |post|
        %h2
          %span.date= post.created_at.strftime("%d/%m/%Y")
          = link_to post.title, post
    - else
      %h2 Aucun article pour le moment.

app/views/posts/new.html.haml
%div.grid_12.prefix_2
  %h1 New post

  = render 'form'

  = link_to 'Back', posts_path

app/views/posts/show.html.haml
%div.grid_12.prefix_2
  %p#notice= notice

  %h2
    = @post.title
    %span.date_s= @post.created_at.strftime("%d/%m/%Y")

  = markdown(@post.content)

  %script
    var idcomments_acct = '0d7fc6a916efae67ca8357dc814edffc';
    var idcomments_post_id;
    var idcomments_post_url;
  %span{ :id => "IDCommentsPostTitle", :style => "display:none"}
  %script{ :type => 'text/javascript', :src => 'http://www.intensedebate.com/js/genericCommentWrapperV2.js'}

  - if current_user
    = link_to 'Edit', edit_post_path(@post)
    \|
    = link_to 'Back', posts_path

app/views/subscribers/_form.haml
%div.sub_form
  = form_for @subscriber do |f|
    -if @subscriber.errors.any?
      #error_explanation
        %h2= "#{pluralize(@subscriber.errors.count, "erreur")} a empéché votre inscription:"
        %ul
          - @subscriber.errors.full_messages.each do |msg|
            %li= msg

    %div.grid_5.alpha.prefix_1
      %p
        Prénom :
        = f.text_field :firstname

      %p
        Nom :
        = f.text_field :lastname

      %p
        Email :
        = f.text_field :email

    %div.grid_7
      %p
        Domaine de travail :
        = f.text_field :work_field

      %p
        = f.label "Status"
        = f.select :status, Settings.status

      %p
        = f.label "Formule"
        = f.select :interest, Settings.interests
    %div.clear
    %div.grid_8.prefix_1
      %p
        = f.label "Commentaire"
        %br
        = f.text_area :comment, :cols => 50, :rows => 6

    %div.clear

    %div.grid_4.prefix_1
      .actions
        = f.submit "M'inscrire"
    %div.clear
    
    = link_to "Retour", root_url

app/views/subscribers/_subscriber.haml
- thec = ""
- if i.odd?
  - thec = "alt"
%tr{:class => thec}
  %td= subscriber.name
  %td= subscriber.email
  %td= subscriber.status
  %td= subscriber.interest
  %td= subscriber.work_field
  %td= link_to 'Supprimer', subscriber, :confirm => 'Etes vous sûr ?', :method => :delete

app/views/subscribers/index.html.haml
%div.grid_14.prefix_1
  %h2 Subscribers
  
  %ul
    %li
      Full :
      = Subscriber.permanent.count
      = "(#{Subscriber.permanent.count * Settings.price.permanent} € / m)"
    %li
      Medium :
      = Subscriber.medium.count
      = "(#{Subscriber.medium.count * Settings.price.medium} € / m)"
    %li
      Short :
      = Subscriber.short.count
      = "(#{Subscriber.short.count * Settings.price.short} € / m)"

    %li
      Total :
      - count = @subscribers.count
      = count
      = " (#{Subscriber.short.count * Settings.price.short + Subscriber.medium.count * Settings.price.medium + Subscriber.permanent.count * Settings.price.permanent} € / m)"
  
  %table
    %tr
      %th Nom
      %th email
      %th Status
      %th Formule
      %th Domaine
      %th
    - i = 0
    - @subscribers.each do |subscriber|
      = render 'subscriber', :subscriber => subscriber, :i => i
      - i += 1

app/views/subscribers/new.html.haml
%div.grid_14.prefix_1
  %div.zap
    %p Ces données nous permettrons d'estimer le nombre de personnes intéressées, elles ne seront pas cédées à des tiers.
    = render 'form', :subscriber => @subscriber